on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm i changelog-parser
      - run: node parse-changelog-for-release.js
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "release.md"
